CREATE DATABASE IF NOT EXISTS bigdt DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'bigdt_user'@'%' IDENTIFIED BY 'bigdt_password';
GRANT ALL PRIVILEGES ON bigdt.* TO 'bigdt_user'@'%';
FLUSH PRIVILEGES;
