# Minimal defaults for Spark Standalone + HDFS
spark.hadoop.fs.defaultFS hdfs://namenode:9000

# Cluster manager
spark.master spark://spark-master:7077

# Resource defaults
spark.executor.memory 1g
spark.executor.cores 2
spark.driver.memory 1g
spark.driver.cores 1

# Runtime
spark.app.name Spark-Application
spark.local.dir /var/lib/spark/work

# Serialization
spark.serializer org.apache.spark.serializer.KryoSerializer
